import type { SolutionPageData } from "@/components/verticals/SolutionPageLayout";

const allVerticals = [
  { label: "Hospitality", href: "/solutions/hospitality" },
  { label: "Corporate", href: "/solutions/corporate" },
  { label: "Fitness", href: "/solutions/fitness" },
  { label: "Industrial", href: "/solutions/industrial" },
  { label: "Events", href: "/solutions/events" },
  { label: "Influencers & Artists", href: "/solutions/influencers-artists" },
];

function getRelated(current: string) {
  return allVerticals.filter((v) => v.href !== current);
}

export const solutionPages: Record<string, SolutionPageData> = {
  hospitality: {
    slug: "hospitality",
    icon: "utensils",
    title: "Hospitality",
    subtitle: "Hotels & Restaurants",
    heroHeadline: "Premium Uniforms for Hotels & Restaurants",
    heroDescription:
      "Factory-direct uniforms, linens, and guest merchandise for hospitality teams that need consistency, durability, and a premium look across every property.",
    heroImage: "/images/solutions/hospitality/hero.jpg",
    heroImageAlt: "Professional hotel staff in premium uniforms",
    overview:
      "Hospitality teams need merchandise that makes the brand feel premium the moment guests see it. Whether you run a boutique hotel, restaurant group, or multi-location property portfolio, your uniforms and amenity items need to look polished, wear well, and stay consistent across locations. We help you do that with factory-direct production, premium cotton-first options, and tighter control over timelines and quality.",
    productShowcaseImage: "/images/solutions/hospitality/product.jpg",
    productShowcaseAlt: "Hotel staff product showcase for hospitality uniforms",
    products: [
      { name: "Staff Uniforms", description: "Polo shirts, dress shirts, and complete uniform sets with embroidered logos. Tailored fits available.", moq: "50 units", priceRange: "€9–18/unit" },
      { name: "Chef Coats & Aprons", description: "Durable chef whites, bistro aprons, and kitchen wear. Heat-resistant fabrics available.", moq: "30 units", priceRange: "€12–25/unit" },
      { name: "Hotel Towels & Linens", description: "Premium cotton towels, bathrobes, and bed linens with woven or embroidered branding.", moq: "100 units", priceRange: "€5–15/unit" },
      { name: "Bathrobes", description: "Luxury terry cloth and waffle-weave bathrobes. Custom sizing and embroidery.", moq: "50 units", priceRange: "€18–35/unit" },
      { name: "Front Desk Apparel", description: "Professional blazers, vests, and accessories for front-of-house staff.", moq: "20 units", priceRange: "€25–50/unit" },
      { name: "Guest Amenity Items", description: "Branded slippers, tote bags, and welcome kits for guest rooms.", moq: "100 units", priceRange: "€3–8/unit" },
    ],
    processImage: "/images/solutions/hospitality/process.jpg",
    processImageAlt: "Hospitality garment production in progress",
    supportImage: "/images/solutions/hospitality/product.jpg",
    supportImageAlt: "Premium hospitality merchandise program details",
    faqs: [
      { question: "What is the minimum order for hotel uniforms?", answer: "Our minimum order quantity starts at 50 units per style. For multi-property orders, we can mix styles within a single order." },
      { question: "Can you match our existing brand colors exactly?", answer: "Yes. We do Pantone color matching for all fabric dyes and embroidery threads. We'll send a color sample for approval before production." },
      { question: "How long does production take?", answer: "Standard production is 4–8 weeks. Rush orders are available in 7–10 days for an additional fee." },
      { question: "Do you offer towel and linen programs?", answer: "Yes. We provide custom towels, bed linens, and bathrobes with woven logos, embroidered branding, or custom labels." },
    ],
    ctaText: "Ready to upgrade your hospitality uniform program?",
    relatedVerticals: getRelated("/solutions/hospitality"),
  },

  corporate: {
    slug: "corporate",
    icon: "building2",
    title: "Corporate",
    subtitle: "Tech & Office Brands",
    heroHeadline: "Branded Merchandise for Modern Companies",
    heroDescription:
      "Premium employee merch, onboarding kits, and client gifts that people actually want to wear, keep, and associate with your brand.",
    heroImage: "/images/solutions/corporate/hero.jpg",
    heroImageAlt: "Corporate office team wearing branded merchandise",
    overview:
      "Corporate merchandise is not just swag. It shapes how employees, candidates, and clients experience your brand in the real world. From onboarding kits to event apparel and premium gifts, we help companies build merchandise programs that feel stronger, wear better, and avoid the cheap synthetic look most teams settle for.",
    productShowcaseImage: "/images/solutions/corporate/product.jpg",
    productShowcaseAlt: "Premium corporate merchandise product showcase",
    productShowcasePosition: "center center",
    productShowcaseAspect: "square",
    products: [
      { name: "Branded Hoodies", description: "Premium cotton and cotton-blend hoodies with embroidered or printed logos. Unisex and fitted options.", moq: "50 units", priceRange: "€16–28/unit" },
      { name: "Corporate Polo Shirts", description: "Piqué and performance polos with custom embroidery. Perfect for team events and everyday office wear.", moq: "50 units", priceRange: "€9–15/unit" },
      { name: "Custom T-Shirts", description: "Heavyweight and lightweight options with screen printing or DTG printing. Multiple color options.", moq: "50 units", priceRange: "€6–12/unit" },
      { name: "Tote Bags & Accessories", description: "Canvas totes, laptop sleeves, and branded accessories for conferences and client gifts.", moq: "100 units", priceRange: "€4–10/unit" },
      { name: "Onboarding Kits", description: "Complete welcome kits with hoodie, tee, mug, and branded items. Custom packaging available.", moq: "25 kits", priceRange: "€35–60/kit" },
      { name: "Client Gift Sets", description: "Premium gift boxes with curated branded merchandise. Custom packaging and personalization.", moq: "25 sets", priceRange: "€30–75/set" },
    ],
    processImage: "/images/solutions/corporate/process.jpg",
    processImageAlt: "Corporate merch screen printing process",
    supportImage: "/images/solutions/corporate/support.jpg",
    supportImageAlt: "Workwear production supporting corporate programs",
    faqs: [
      { question: "Can you handle multi-location deliveries?", answer: "Yes. We can ship to multiple offices across Europe and America. Each location gets its own tracking number." },
      { question: "Do you offer design services?", answer: "Yes. Our design team can help with logo placement, color selection, and mockup creation — included in your quote." },
      { question: "What about reorders?", answer: "Reorders are simple. We keep your specifications on file, so subsequent orders are faster and easier." },
      { question: "Can we get samples before placing a large order?", answer: "Absolutely. We offer sample production for a small fee, which is credited against your first order." },
    ],
    ctaText: "Ready to make your company merch worth wearing?",
    relatedVerticals: getRelated("/solutions/corporate"),
  },

  fitness: {
    slug: "fitness",
    icon: "dumbbell",
    title: "Fitness",
    subtitle: "Gyms & Activewear",
    heroHeadline: "Custom Activewear for Gyms & Fitness Brands",
    heroDescription:
      "Performance-driven activewear and branded gym merch designed to look premium on the floor, in the studio, and outside the gym.",
    heroImage: "/images/solutions/fitness/hero.jpg",
    heroImageAlt: "Gym members wearing premium branded activewear",
    overview:
      "Fitness brands live or die by how the product feels when it is worn. Your members will not keep wearing weak fabrics, poor fits, or forgettable branding. We help gyms, studios, and activewear brands create stronger merchandise with better fabric direction, sharper fit logic, and factory-direct production that protects margin.",
    productShowcaseImage: "/images/solutions/fitness/product.jpg",
    productShowcaseAlt: "Premium gym wear product showcase",
    productShowcasePosition: "center center",
    productShowcaseAspect: "square",
    products: [
      { name: "Performance Tank Tops", description: "Moisture-wicking, breathable tank tops with printed or sublimated branding. Multiple fit options.", moq: "50 units", priceRange: "€7–12/unit" },
      { name: "Athletic T-Shirts", description: "Lightweight technical tees with DRI-FIT style fabric. Ideal for training and daily wear.", moq: "50 units", priceRange: "€8–14/unit" },
      { name: "Training Shorts", description: "Performance shorts with zipper pockets and branded waistband. Multiple lengths available.", moq: "50 units", priceRange: "€10–18/unit" },
      { name: "Compression Leggings", description: "High-quality compression tights with sublimated designs. Women's and men's styles.", moq: "50 units", priceRange: "€14–22/unit" },
      { name: "Gym Hoodies", description: "Heavyweight cotton-blend hoodies for post-workout. Embroidered or printed logos.", moq: "50 units", priceRange: "€16–25/unit" },
      { name: "Gym Bags & Accessories", description: "Branded duffle bags, towels, shaker bottles, and resistance bands.", moq: "100 units", priceRange: "€5–15/unit" },
    ],
    processImage: "/images/solutions/fitness/process.jpg",
    processImageAlt: "Fitness apparel production process",
    supportImage: "/images/solutions/fitness/support.jpg",
    supportImageAlt: "Sock knitting and specialist fitness production equipment",
    faqs: [
      { question: "What fabric options are available for activewear?", answer: "We offer polyester, nylon, spandex blends, and technical moisture-wicking fabrics. We can source specific fabric compositions on request." },
      { question: "Can you do sublimation printing for all-over designs?", answer: "Yes. We offer both sublimation and screen printing. Sublimation works best on polyester fabrics for all-over designs." },
      { question: "Do you offer size runs for retail?", answer: "Yes. We can produce full size runs (XS–3XL) with individual size labels and retail-ready packaging." },
      { question: "What about sustainability options?", answer: "We offer recycled polyester and organic cotton options for eco-conscious fitness brands. OEKO-TEX certified." },
    ],
    ctaText: "Ready to launch a gym merch line people actually wear?",
    relatedVerticals: getRelated("/solutions/fitness"),
  },

  industrial: {
    slug: "industrial",
    icon: "hardhat",
    title: "Industrial",
    subtitle: "Workwear & PPE",
    heroHeadline: "Durable Workwear & Industrial Uniforms",
    heroDescription:
      "Safety-conscious, durable workwear built for demanding environments where comfort, compliance, and brand consistency all matter.",
    heroImage: "/images/solutions/industrial/hero.jpg",
    heroImageAlt: "Industrial workers wearing branded workwear",
    overview:
      "Industrial uniforms need to do more than carry a logo. They have to hold up under pressure, support compliance requirements, and still represent your company professionally. We produce workwear programs that balance durability, safety, visibility, and brand consistency without sending you through distributor markup chains.",
    productShowcaseImage: "/images/solutions/industrial/product.jpg",
    productShowcaseAlt: "Industrial workwear production showcase",
    productShowcasePosition: "center 12%",
    products: [
      { name: "Work Uniforms", description: "Durable poly-cotton work shirts and pants with embroidered company branding. Industrial wash resistant.", moq: "50 units", priceRange: "€15–28/unit" },
      { name: "Hi-Vis Jackets", description: "EN ISO 20471 compliant high-visibility jackets with reflective strips and custom branding.", moq: "50 units", priceRange: "€22–40/unit" },
      { name: "Coveralls", description: "Full-body coveralls in various fabrics. Flame-resistant and anti-static options available.", moq: "30 units", priceRange: "€25–50/unit" },
      { name: "Safety Vests", description: "Lightweight reflective vests with printed company logos. Class 2 and Class 3 options.", moq: "100 units", priceRange: "€5–12/unit" },
      { name: "Work Polo Shirts", description: "Heavy-duty polo shirts suitable for workshop environments. Embroidered branding.", moq: "50 units", priceRange: "€10–18/unit" },
      { name: "Work Accessories", description: "Branded hard hat stickers, tool bags, and work gloves with company branding.", moq: "100 units", priceRange: "€3–10/unit" },
    ],
    processImage: "/images/solutions/industrial/process.jpg",
    processImageAlt: "Industrial knitting and technical machinery in production",
    supportImage: "/images/solutions/industrial/support.jpg",
    supportImageAlt: "Towel and textile production supporting industrial textile programs",
    faqs: [
      { question: "Do your products meet European safety standards?", answer: "Yes. Our industrial products comply with relevant EN/ISO standards. We provide compliance documentation with every order." },
      { question: "Can you produce flame-resistant workwear?", answer: "Yes. We source certified flame-resistant fabrics and can produce FR coveralls, jackets, and shirts." },
      { question: "What about ongoing supply agreements?", answer: "We offer annual supply agreements with locked-in pricing and priority production slots for regular orders." },
      { question: "How durable are your industrial uniforms?", answer: "Our industrial uniforms are designed for 100+ commercial washes. We use reinforced stitching and industrial-grade fabrics." },
    ],
    ctaText: "Ready to equip your workforce with better workwear?",
    relatedVerticals: getRelated("/solutions/industrial"),
  },

  events: {
    slug: "events",
    icon: "partypopper",
    title: "Events",
    subtitle: "Festivals & Tours",
    heroHeadline: "Branded Merchandise for Events & Festivals",
    heroDescription:
      "From festival tees to crew apparel, we produce event merchandise built to sell, look premium, and arrive when timing matters most.",
    heroImage: "/images/solutions/events/hero.jpg",
    heroImageAlt: "Festival and event crowd wearing branded merchandise",
    overview:
      "Event merch has two jobs: create revenue and make the experience feel bigger. Whether you are running a music festival, corporate conference, or tour, your products need to look intentional, arrive on time, and hold margin under pressure. We help event teams launch faster with factory-direct pricing, rush options, and merchandise that feels like part of the brand experience.",
    productShowcaseImage: "/images/solutions/events/product.jpg",
    productShowcaseAlt: "Premium event merchandise product showcase",
    productShowcasePosition: "center center",
    productShowcaseAspect: "square",
    products: [
      { name: "Event T-Shirts", description: "High-quality cotton tees with screen printing or DTG. Perfect for festival and event merchandise.", moq: "100 units", priceRange: "€6–10/unit" },
      { name: "Crew Apparel", description: "Branded staff and crew uniforms including polos, jackets, and lanyards.", moq: "30 units", priceRange: "€10–22/unit" },
      { name: "VIP Merchandise", description: "Premium limited-edition items for VIP packages — hoodies, caps, exclusive tees.", moq: "25 units", priceRange: "€18–35/unit" },
      { name: "Caps & Beanies", description: "Embroidered or printed caps, snapbacks, and beanies with event branding.", moq: "100 units", priceRange: "€5–12/unit" },
      { name: "Festival Gear", description: "Bandanas, wristbands, tote bags, and flags with event artwork.", moq: "200 units", priceRange: "€2–8/unit" },
      { name: "Tour Merchandise", description: "Complete tour merch packages with multiple designs and size runs.", moq: "200 units", priceRange: "€5–15/unit" },
    ],
    processImage: "/images/solutions/events/process.jpg",
    processImageAlt: "Fast event merchandise printing process",
    supportImage: "/images/solutions/events/support.jpg",
    supportImageAlt: "Event logistics facility and delivery operations",
    faqs: [
      { question: "Can you handle rush orders for last-minute events?", answer: "Yes. We offer rush production in 7–10 days for event merchandise. Contact us immediately for availability." },
      { question: "Do you offer merchandise sales at events?", answer: "We produce the merchandise; you handle sales. However, we can advise on sizing, quantities, and pricing strategy." },
      { question: "What's the minimum order for event tees?", answer: "100 units minimum for screen-printed tees. Lower minimums available for DTG printing." },
      { question: "Can you produce different designs for different events?", answer: "Absolutely. We can handle multiple designs in a single order with different artworks and sizes." },
    ],
    ctaText: "Ready to launch event merch that actually moves?",
    relatedVerticals: getRelated("/solutions/events"),
  },

  "influencers-artists": {
    slug: "influencers-artists",
    icon: "music2",
    title: "Influencers & Artists",
    subtitle: "Creator Merch",
    heroHeadline: "Launch Your Brand. We Handle the Rest.",
    heroDescription:
      "A one-stop merch production system for creators who want premium drops, stronger margins, and fewer operational headaches.",
    heroImage: "/images/solutions/influencers/hero.jpg",
    heroImageAlt: "Content creator preparing a premium merchandise launch",
    overview:
      "For creators, merch is not filler revenue. It is brand identity, community glue, and proof that people want to buy deeper into your world. We help musicians, artists, creators, and community-led brands turn that opportunity into real product with design support, production control, better material direction, and a smoother path from first idea to repeat drop.",
    productShowcaseImage: "/images/solutions/influencers/product.jpg",
    productShowcaseAlt: "Premium creator merchandise showcase",
    productShowcasePosition: "center center",
    productShowcaseAspect: "square",
    products: [
      { name: "Merch Drop Collections", description: "Complete collection production — tees, hoodies, accessories. Perfect for limited drops and seasonal launches.", moq: "50 units", priceRange: "€8–25/unit" },
      { name: "Branded Apparel", description: "Premium hoodies, tees, and jackets with your branding. Embroidered, screen printed, or DTG.", moq: "50 units", priceRange: "€10–30/unit" },
      { name: "Community Gear", description: "Branded items for your community — caps, bags, stickers, and accessories.", moq: "100 units", priceRange: "€3–12/unit" },
      { name: "Limited Editions", description: "Small-batch premium items for exclusive drops — numbered editions, special packaging.", moq: "25 units", priceRange: "€20–50/unit" },
      { name: "Custom Packaging", description: "Branded mailer bags, tissue paper, stickers, and thank-you cards for the unboxing experience.", moq: "100 units", priceRange: "€1–5/unit" },
      { name: "Full-Service Design", description: "Our design team creates your merch designs from concept to production-ready artwork.", moq: "N/A", priceRange: "From €150" },
    ],
    processImage: "/images/solutions/influencers/process.jpg",
    processImageAlt: "Professional creator merch drop setup",
    supportImage: "/images/solutions/influencers/support.jpg",
    supportImageAlt: "Digital printing options for creator merchandise",
    faqs: [
      { question: "Can you help design my merch if I don't have artwork?", answer: "Yes! Our design team can create designs from scratch based on your brand identity, references, and vision. Design services start at €150." },
      { question: "What's the best approach for a first merch drop?", answer: "Start with 2–3 core items (tee, hoodie, cap) in limited quantities. This tests demand with lower risk. We can help plan your drop strategy." },
      { question: "Can you handle fulfillment and shipping?", answer: "We produce and deliver your order to you or your warehouse. For individual customer fulfillment, we recommend partnering with a 3PL service." },
      { question: "How do I get started?", answer: "Send us your ideas, brand references, and quantity estimates. We'll provide a quote within 2 hours and mockups within 24 hours." },
    ],
    ctaText: "Ready to build a merch drop your audience wants to keep?",
    relatedVerticals: getRelated("/solutions/influencers-artists"),
  },
};
