import { CATEGORIES, MOQ, type ProductCategory } from "@/lib/pricing";
import type {
  ApprovalItem,
  BrandAsset,
  CatalogItem,
  PortalDataBundle,
  PortalOrder,
  PortalProfile,
  QuoteRequest,
} from "@/lib/portal/types";

const catalogSeed: CatalogItem[] = [
  {
    id: "cat-hoodie",
    slug: "premium-cotton-hoodie",
    title: "Premium Cotton Hoodie",
    category: "Apparel",
    subcategory: "Hoodies",
    description: "Heavyweight cotton fleece with premium trims for staff, events, and retail drops.",
    material: "Organic Cotton",
    colorFamily: "Navy",
    minPrice: 42.5,
    image: "/images/solutions/corporate/product.jpg",
    badge: "Best Seller",
    moq: 50,
  },
  {
    id: "cat-mug",
    slug: "matte-ceramic-mug",
    title: "Matte Ceramic Mug",
    category: "Drinkware",
    subcategory: "Mugs",
    description: "Minimal matte ceramic mug for onboarding kits, client gifts, and branded sets.",
    material: "Ceramic",
    colorFamily: "White",
    minPrice: 12,
    image: "/images/solutions/corporate/process.jpg",
    moq: 100,
  },
  {
    id: "cat-tote",
    slug: "eco-friendly-tote-bag",
    title: "Eco-friendly Tote Bag",
    category: "Accessories",
    subcategory: "Tote Bags",
    description: "Canvas tote with reinforced handles and premium print area.",
    material: "Organic Cotton",
    colorFamily: "Natural",
    minPrice: 18.9,
    image: "/images/solutions/events/product.jpg",
    badge: "New Arrival",
    moq: 100,
  },
  {
    id: "cat-bottle",
    slug: "insulated-water-bottle",
    title: "Insulated Water Bottle",
    category: "Drinkware",
    subcategory: "Bottles",
    description: "Double-wall insulated stainless steel bottle for premium client gifting.",
    material: "Stainless Steel",
    colorFamily: "Steel",
    minPrice: 34,
    image: "/images/solutions/fitness/product.jpg",
    moq: 50,
  },
  {
    id: "cat-cap",
    slug: "adjustable-dad-cap",
    title: "Adjustable Dad Cap",
    category: "Accessories",
    subcategory: "Caps",
    description: "Unstructured cap designed for embroidery-ready everyday wear.",
    material: "Cotton Twill",
    colorFamily: "Navy",
    minPrice: 22,
    image: "/images/solutions/influencers/product.jpg",
    moq: 50,
  },
  {
    id: "cat-polo",
    slug: "premium-pique-polo",
    title: "Premium Pique Polo",
    category: "Apparel",
    subcategory: "Polos",
    description: "Structured pique polo for hospitality teams and enterprise uniforms.",
    material: "Pique Cotton",
    colorFamily: "White",
    minPrice: 38,
    image: "/images/solutions/hospitality/product.jpg",
    moq: 50,
  },
  {
    id: "cat-bomber",
    slug: "fleece-lined-bomber",
    title: "Fleece-lined Bomber",
    category: "Apparel",
    subcategory: "Outerwear",
    description: "Premium outerwear with elevated trims and durable lining.",
    material: "Recycled Polyester",
    colorFamily: "Olive",
    minPrice: 85,
    image: "/images/solutions/industrial/product.jpg",
    moq: 50,
  },
  {
    id: "cat-notebook",
    slug: "minimalist-desktop-notebook",
    title: "Minimalist Desktop Notebook",
    category: "Office",
    subcategory: "Stationery",
    description: "High-GSM recycled notebook for onboarding kits and events.",
    material: "Recycled Paper",
    colorFamily: "Stone",
    minPrice: 24,
    image: "/images/solutions/corporate/support.jpg",
    moq: 100,
  },
];

function buildQuoteFromProduct(productName: string, category: ProductCategory) {
  return {
    productName,
    category: CATEGORIES[category].label,
    quantity: MOQ[category].standard,
  };
}

export function buildMockPortalBundle(profile: PortalProfile): PortalDataBundle {
  const quoteBase = buildQuoteFromProduct("Premium Cotton Hoodie", "basic-apparel");

  const quotes: QuoteRequest[] = [
    {
      id: "quote-techcorp-001",
      userId: profile.id,
      title: "Tech onboarding hoodie pack",
      category: quoteBase.category,
      productName: quoteBase.productName,
      quantity: 250,
      decorationMethod: "Embroidery",
      rush: false,
      unitPriceMin: 18.5,
      unitPriceMax: 22.25,
      totalMin: 4625,
      totalMax: 5562.5,
      leadTime: "3–5 weeks",
      destination: "United States",
      shippingMethod: "Standard Ground",
      notes: "Navy base, chest embroidery, gift-ready presentation.",
      status: "submitted",
      createdAt: "2026-04-10T09:30:00.000Z",
      linkedAssetIds: ["asset-logo-tech", "asset-brand-guide"],
    },
    {
      id: "quote-techcorp-002",
      userId: profile.id,
      title: "Executive gift mug concept",
      category: "Drinkware",
      productName: "Matte Ceramic Mug",
      quantity: 120,
      decorationMethod: "Screen Print",
      rush: false,
      unitPriceMin: 10.8,
      unitPriceMax: 12,
      totalMin: 1296,
      totalMax: 1440,
      leadTime: "3–5 weeks",
      destination: "Germany",
      shippingMethod: "Standard Ground",
      notes: "Matte charcoal mug for Q3 client gifting.",
      status: "draft",
      createdAt: "2026-04-15T12:15:00.000Z",
      linkedAssetIds: [],
    },
  ];

  const orders: PortalOrder[] = [
    {
      id: "order-techcorp-001",
      userId: profile.id,
      orderNumber: "MM-8492",
      productName: "Premium Cotton Hoodies",
      category: "Apparel",
      quantity: 250,
      totalAmount: 5562.5,
      currency: "USD",
      status: "in-production",
      statusLabel: "In Production",
      deliveryDate: "2026-05-18",
      createdAt: "2026-04-12T09:30:00.000Z",
      reorderQuoteId: quotes[0].id,
      events: [
        {
          id: "evt-1",
          orderId: "order-techcorp-001",
          label: "Order confirmed",
          description: "Deposit received and production slot reserved.",
          createdAt: "2026-04-12T09:30:00.000Z",
          state: "done",
        },
        {
          id: "evt-2",
          orderId: "order-techcorp-001",
          label: "Batch processing",
          description: "Embroidery setup and thread matching completed.",
          createdAt: "2026-04-13T14:15:00.000Z",
          state: "done",
        },
        {
          id: "evt-3",
          orderId: "order-techcorp-001",
          label: "Quality control",
          description: "Inline QC is underway prior to packing.",
          createdAt: "2026-04-18T08:00:00.000Z",
          state: "current",
        },
        {
          id: "evt-4",
          orderId: "order-techcorp-001",
          label: "Shipment",
          description: "Export booking will be confirmed after QC sign-off.",
          createdAt: "2026-05-02T08:00:00.000Z",
          state: "upcoming",
        },
      ],
    },
    {
      id: "order-techcorp-002",
      userId: profile.id,
      orderNumber: "MM-7310",
      productName: "Executive Laptop Sleeves",
      category: "Accessories",
      quantity: 100,
      totalAmount: 2200,
      currency: "USD",
      status: "delivered",
      statusLabel: "Delivered",
      deliveryDate: "2026-03-28",
      createdAt: "2026-03-01T10:00:00.000Z",
      reorderQuoteId: undefined,
      events: [],
    },
  ];

  const assets: BrandAsset[] = [
    {
      id: "asset-logo-tech",
      userId: profile.id,
      name: "Technology logo primary.svg",
      type: "SVG",
      mimeType: "image/svg+xml",
      sizeLabel: "1.2 MB",
      linkedTo: "account",
      storagePath: "mock/technology-logo-primary.svg",
      createdAt: "2026-04-08T12:30:00.000Z",
      status: "ready",
    },
    {
      id: "asset-brand-guide",
      userId: profile.id,
      name: "Brand_guidelines_2026.pdf",
      type: "PDF",
      mimeType: "application/pdf",
      sizeLabel: "4.8 MB",
      linkedTo: "quote",
      linkedId: quotes[0].id,
      storagePath: "mock/brand-guidelines-2026.pdf",
      createdAt: "2026-04-10T10:15:00.000Z",
      status: "ready",
    },
  ];

  const approvals: ApprovalItem[] = [
    {
      id: "approval-1",
      userId: profile.id,
      title: "Approve hoodie embroidery proof",
      status: "pending",
      dueLabel: "Due in 2 days",
    },
  ];

  return {
    profile,
    dashboard: {
      activeOrders: orders.filter((order) => order.status !== "delivered").length,
      totalSpent: orders.reduce((sum, order) => sum + order.totalAmount, 0),
      repeatOrders: orders.length + 10,
      pendingApprovals: approvals.filter((approval) => approval.status === "pending").length,
    },
    orders,
    catalogItems: catalogSeed,
    quotes,
    assets,
    approvals,
  };
}
