import { CATEGORIES, MOQ, type ProductCategory } from "@/lib/pricing";
import type {
  ApprovalItem,
  BrandAsset,
  CatalogItem,
  PortalDataBundle,
  PortalOrder,
  PortalProfile,
  QuoteRequest,
} from "@/lib/portal/types";

export const catalogSeed: CatalogItem[] = [
  {
    id: "cat-hoodie",
    slug: "premium-cotton-hoodie",
    title: "Premium Cotton Hoodie",
    category: "Apparel",
    subcategory: "Hoodies",
    description: "Premium fleece hoodie built for brand programs that need heavier cotton feel, clean embroidery, and dependable repeat production.",
    material: "Organic Cotton Fleece",
    colorFamily: "Navy",
    sku: "MM-HOOD-001",
    minPrice: 42.5,
    maxPrice: 48,
    image: "/images/solutions/corporate/product.jpg",
    badge: "Best Seller",
    moq: 50,
    leadTimeDays: 28,
    leadTimeLabel: "3-5 weeks production plus shipping",
    decorationMethods: ["embroidery", "screen-print", "dtg"],
    variants: ["Navy", "Black", "Heather Grey"],
  },
  {
    id: "cat-mug",
    slug: "matte-ceramic-mug",
    title: "Matte Ceramic Mug",
    category: "Drinkware",
    subcategory: "Mugs",
    description: "Matte ceramic mug for gifting programs with clean print coverage and presentation-ready retail feel.",
    material: "Ceramic",
    colorFamily: "White",
    sku: "MM-MUG-002",
    minPrice: 12,
    maxPrice: 14,
    image: "/images/solutions/corporate/process.jpg",
    moq: 100,
    leadTimeDays: 24,
    leadTimeLabel: "3-4 weeks production plus shipping",
    decorationMethods: ["screen-print", "sublimation"],
    variants: ["White", "Charcoal"],
  },
  {
    id: "cat-tote",
    slug: "eco-friendly-tote-bag",
    title: "Eco-friendly Tote Bag",
    category: "Accessories",
    subcategory: "Tote Bags",
    description: "Structured canvas tote with reinforced handles and a large decoration area for events, retail, and corporate kits.",
    material: "Organic Cotton Canvas",
    colorFamily: "Natural",
    sku: "MM-TOTE-003",
    minPrice: 18.9,
    maxPrice: 21.5,
    image: "/images/solutions/events/product.jpg",
    badge: "New Arrival",
    moq: 100,
    leadTimeDays: 21,
    leadTimeLabel: "3-4 weeks production plus shipping",
    decorationMethods: ["screen-print", "embroidery", "dtg"],
    variants: ["Natural", "Black", "Olive"],
  },
  {
    id: "cat-bottle",
    slug: "insulated-water-bottle",
    title: "Insulated Water Bottle",
    category: "Drinkware",
    subcategory: "Bottles",
    description: "Double-wall stainless bottle for premium gifting with strong laser or print compatibility and transit-safe packaging.",
    material: "Stainless Steel",
    colorFamily: "Steel",
    sku: "MM-BOTTLE-004",
    minPrice: 34,
    maxPrice: 38,
    image: "/images/solutions/fitness/product.jpg",
    moq: 50,
    leadTimeDays: 26,
    leadTimeLabel: "3-4 weeks production plus shipping",
    decorationMethods: ["screen-print", "laser"],
    variants: ["Steel", "Black"],
  },
  {
    id: "cat-cap",
    slug: "adjustable-dad-cap",
    title: "Adjustable Dad Cap",
    category: "Accessories",
    subcategory: "Caps",
    description: "Cotton twill cap designed for embroidery-led programs, events, and fast-moving evergreen merchandise.",
    material: "Cotton Twill",
    colorFamily: "Navy",
    sku: "MM-CAP-005",
    minPrice: 22,
    maxPrice: 26,
    image: "/images/solutions/influencers/product.jpg",
    moq: 50,
    leadTimeDays: 20,
    leadTimeLabel: "2-4 weeks production plus shipping",
    decorationMethods: ["embroidery", "screen-print"],
    variants: ["Navy", "Stone", "Black"],
  },
  {
    id: "cat-polo",
    slug: "premium-pique-polo",
    title: "Premium Pique Polo",
    category: "Apparel",
    subcategory: "Polos",
    description: "Pique polo made for hospitality and enterprise teams that need a smarter hand feel and consistent logo placement.",
    material: "Pique Cotton 220 GSM benchmark",
    colorFamily: "White",
    sku: "MM-POLO-006",
    minPrice: 38,
    maxPrice: 44,
    image: "/images/solutions/hospitality/product.jpg",
    moq: 50,
    leadTimeDays: 24,
    leadTimeLabel: "3-4 weeks production plus shipping",
    decorationMethods: ["embroidery", "screen-print"],
    variants: ["White", "Navy", "Black"],
  },
  {
    id: "cat-bomber",
    slug: "fleece-lined-bomber",
    title: "Fleece-lined Bomber",
    category: "Apparel",
    subcategory: "Outerwear",
    description: "Premium bomber jacket with elevated trims and lining for staff uniforms, retail drops, and colder-weather programs.",
    material: "Recycled Polyester",
    colorFamily: "Olive",
    sku: "MM-BOMBER-007",
    minPrice: 85,
    maxPrice: 94,
    image: "/images/solutions/industrial/product.jpg",
    moq: 50,
    leadTimeDays: 32,
    leadTimeLabel: "4-6 weeks production plus shipping",
    decorationMethods: ["embroidery", "screen-print"],
    variants: ["Olive", "Black"],
  },
  {
    id: "cat-notebook",
    slug: "minimalist-desktop-notebook",
    title: "Minimalist Desktop Notebook",
    category: "Office",
    subcategory: "Stationery",
    description: "Recycled notebook with higher-GSM pages, clean deboss options, and gifting-ready finishing for executive kits.",
    material: "Recycled Paper",
    colorFamily: "Stone",
    sku: "MM-NOTE-008",
    minPrice: 24,
    maxPrice: 28,
    image: "/images/solutions/corporate/support.jpg",
    moq: 100,
    leadTimeDays: 18,
    leadTimeLabel: "2-3 weeks production plus shipping",
    decorationMethods: ["screen-print", "deboss"],
    variants: ["Stone", "Black"],
  },
];

function buildQuoteFromProduct(productName: string, category: ProductCategory) {
  return {
    productName,
    category: CATEGORIES[category].label,
    quantity: MOQ[category].standard,
  };
}

export function buildMockPortalBundle(profile: PortalProfile): PortalDataBundle {
  const quoteBase = buildQuoteFromProduct("Premium Cotton Hoodie", "basic-apparel");

  const quotes: QuoteRequest[] = [
    {
      id: "quote-techcorp-001",
      userId: profile.id,
      title: "Tech onboarding hoodie pack",
      category: quoteBase.category,
      productName: quoteBase.productName,
      quantity: 250,
      decorationMethod: "Embroidery",
      rush: false,
      unitPriceMin: 18.5,
      unitPriceMax: 22.25,
      totalMin: 4625,
      totalMax: 5562.5,
      leadTime: "3–5 weeks",
      destination: "United States",
      shippingMethod: "Air Freight Priority",
      notes:
        "Navy base, chest embroidery, gift-ready presentation. Client may request heavier GSM and wants designer support if the embroidery placement needs a 3D proof.",
      status: "submitted",
      createdAt: "2026-04-10T09:30:00.000Z",
      updatedAt: "2026-04-10T09:30:00.000Z",
      assignedTo: "ops@merchmaverick.com",
      internalNotes: "Priority client. Confirm Pantone navy thread before quoting.",
      linkedAssetIds: ["asset-logo-tech", "asset-brand-guide"],
    },
    {
      id: "quote-techcorp-002",
      userId: profile.id,
      title: "Executive gift mug concept",
      category: "Drinkware",
      productName: "Matte Ceramic Mug",
      quantity: 120,
      decorationMethod: "Screen Print",
      rush: false,
      unitPriceMin: 10.8,
      unitPriceMax: 12,
      totalMin: 1296,
      totalMax: 1440,
      leadTime: "3–5 weeks",
      destination: "Germany",
      shippingMethod: "Sea Freight",
      notes:
        "Matte charcoal mug for Q3 client gifting. Keep sea freight pricing unless the client upgrades for a tighter event timeline.",
      status: "draft",
      createdAt: "2026-04-15T12:15:00.000Z",
      updatedAt: "2026-04-15T12:15:00.000Z",
      linkedAssetIds: [],
    },
  ];

  const orders: PortalOrder[] = [
    {
      id: "order-techcorp-001",
      userId: profile.id,
      orderNumber: "MM-8492",
      productName: "Premium Cotton Hoodies",
      category: "Apparel",
      quantity: 250,
      totalAmount: 5562.5,
      currency: "USD",
      status: "in-production",
      statusLabel: "In Production",
      deliveryDate: "2026-05-18",
      createdAt: "2026-04-12T09:30:00.000Z",
      updatedAt: "2026-04-18T08:00:00.000Z",
      assignedTo: "ops@merchmaverick.com",
      internalNotes:
        "Confirm whether the client wants a physical sample before the bulk run. Any heavier GSM or packaging upgrade should be added as a manual surcharge.",
      sourceQuoteId: quotes[0].id,
      reorderQuoteId: quotes[0].id,
      events: [
        {
          id: "evt-1",
          orderId: "order-techcorp-001",
          label: "Quote approved & deposit received",
          description: "Commercial terms were cleared, deposit was secured, and the production slot is now reserved.",
          createdAt: "2026-04-12T09:30:00.000Z",
          state: "done",
        },
        {
          id: "evt-2",
          orderId: "order-techcorp-001",
          label: "Artwork approved & production released",
          description: "Embroidery setup, thread matching, and production release were approved after artwork review.",
          createdAt: "2026-04-13T14:15:00.000Z",
          state: "done",
        },
        {
          id: "evt-3",
          orderId: "order-techcorp-001",
          label: "Quality check in progress",
          description: "Inline QC and packing checks are underway before shipment booking is finalized.",
          createdAt: "2026-04-18T08:00:00.000Z",
          state: "current",
        },
        {
          id: "evt-4",
          orderId: "order-techcorp-001",
          label: "Shipment booked & final balance due",
          description: "Air or sea dispatch will be confirmed after QC sign-off and final balance clearance.",
          createdAt: "2026-05-02T08:00:00.000Z",
          state: "upcoming",
        },
      ],
    },
    {
      id: "order-techcorp-002",
      userId: profile.id,
      orderNumber: "MM-7310",
      productName: "Executive Laptop Sleeves",
      category: "Accessories",
      quantity: 100,
      totalAmount: 2200,
      currency: "USD",
      status: "delivered",
      statusLabel: "Delivered",
      deliveryDate: "2026-03-28",
      createdAt: "2026-03-01T10:00:00.000Z",
      updatedAt: "2026-03-28T10:00:00.000Z",
      reorderQuoteId: undefined,
      events: [],
    },
  ];

  const assets: BrandAsset[] = [
    {
      id: "asset-logo-tech",
      userId: profile.id,
      name: "Technology logo primary.svg",
      type: "SVG",
      mimeType: "image/svg+xml",
      sizeLabel: "1.2 MB",
      linkedTo: "account",
      storagePath: "mock/technology-logo-primary.svg",
      createdAt: "2026-04-08T12:30:00.000Z",
      status: "ready",
    },
    {
      id: "asset-brand-guide",
      userId: profile.id,
      name: "Brand_guidelines_2026.pdf",
      type: "PDF",
      mimeType: "application/pdf",
      sizeLabel: "4.8 MB",
      linkedTo: "quote",
      linkedId: quotes[0].id,
      storagePath: "mock/brand-guidelines-2026.pdf",
      createdAt: "2026-04-10T10:15:00.000Z",
      status: "ready",
    },
  ];

  const approvals: ApprovalItem[] = [
    {
      id: "approval-1",
      userId: profile.id,
      title: "Approve hoodie embroidery proof",
      status: "pending",
      dueLabel: "Due in 2 days",
      linkedRecordType: "quote",
      linkedRecordId: quotes[0].id,
      notes: "Awaiting approval of the chest embroidery proof before production proceeds.",
    },
  ];

  return {
    profile,
    dashboard: {
      activeOrders: orders.filter((order) => order.status !== "delivered").length,
      totalSpent: orders.reduce((sum, order) => sum + order.totalAmount, 0),
      repeatOrders: orders.length + 10,
      pendingApprovals: approvals.filter((approval) => approval.status === "pending").length,
    },
    orders,
    catalogItems: catalogSeed,
    quotes,
    assets,
    approvals,
  };
}
